# Do not double-build branches and PRs from this repo, as PRs won't get merged if they are not up to date
if: repo != head_repo

language: minimal
env:
  global:
    - GRAVIS_REPO="https://github.com/DanySK/Gravis-CI.git"
    - GRAVIS="$HOME/gravis"
    - JDK="adopt@1.8"
before_install:
  - travis_retry git clone --depth 1 $GRAVIS_REPO $GRAVIS
  - source $GRAVIS/install-jdk
  - openssl aes-256-cbc -K $encrypted_f778b2e1574b_key -iv $encrypted_f778b2e1574b_iv -in secrets.asc.enc -out secrets.asc -d
  - export ORG_GRADLE_PROJECT_signingKey=$(cat secrets.asc)
  - rm secrets.asc
  - ./gradlew publish
